export { service as commonService } from '@/features/common/service'
export { service as homeService } from '@/features/home/service'
export { service as authService } from '@/features/auth/service'
export { service as orderService } from '@/features/order/service'
export { service as mineService } from '@/features/mine/service'
export { service as productService } from '@/features/product/service'
